### ISSUE TITLE
Can't read keys at the root

### ISSUE THREAD

**Issue by pmbanugo** [urfave/cli-altsrc#12]
given this TOML file:

```toml
name = "myapp"
image = "nginx:latest"
host = "myapp.example.com"
server = "user@server.example.com"

tester = "tester@example.com"

[greet]
name = "Berry 2"
enthusiasm = "eleven"
```

I can only read greet.name and not the name or image keys at the root.

I tried `Sources: altsrc.TOML("name", "config.toml")` and `Sources: altsrc.TOML(".name", "config.toml")` and no luck. Same for JSOn config as well.

What's the right way or is this a bug?
